/****** Script for SelectTopNRows command from SSMS  ******/
SELECT TOP (1000) [SupplierTransactionID]
      ,[SupplierID]
      ,[TransactionTypeID]
      ,[PurchaseOrderID]
      ,[PaymentMethodID]
      ,[SupplierInvoiceNumber]
      ,[TransactionDate]
      ,[AmountExcludingTax]
      ,[TaxAmount]
      ,[TransactionAmount]
      ,[OutstandingBalance]
      ,[FinalizationDate]
      ,[IsFinalized]
      ,[LastEditedBy]
      ,[LastEditedWhen]
  FROM [WideWorldImporters].[Purchasing].[SupplierTransactions]
  --FROM [WideWorldImporters].[Purchasing].[SupplierTransactions]
 Select * From [WideWorldImporters].[Purchasing].[SupplierTransactions] 
 Where (TransactionDate > '2013-05-27')
